winnow-rs/winnow

src/bytes/streaming.rs
src/character/streaming.rs
src/input.rs
src/number/streaming.rs

In #3, I split the `InputSplitAtPosition` trait but I named it for the
naming direction I assumed I was going.  I've backed off from that and
am naming it to match everything else, for now.

fix(input): Associate Partial trat with Streaming 

---

src/lib.rs
src/parser.rs

`Finish` has no purpose out of extending `IResult`, so this makes that clearer.  I went ahead and left off the `Ext` suffix.
To make this even easier to discover, I advertise it as part of a new `prelude`.

fix(parser): Clarify FinishIResult extends IResult

---

src/input.rs

I was experimenting with adding more trait impls but want this in regardless of what happens with that other work.
This makes it easier to audit what is happening.

style(input): Clean up code

---

src/character/mod.rs

Instead of removing them, like in #2, we'll deprecate them so people have a smoother upgrade path

fix: Deprecate character::is_* functions

---

src/bits/mod.rs
src/bits/tests.rs
src/character/mod.rs

This is prep for merged complete/streaming.
As I expect all `streaming` and `complete` mods to be deprecated, I've
isolated there tests to those mods.  When we add the merged versions,
that'll be too many tests for the `mod.rs` files (and requires more
recompilation), so I'm moving these out to tests.rs.

refactor(tests): Move all tests out of mod 

---

src/bytes/complete.rs
src/bytes/streaming.rs
src/character/complete.rs
src/character/streaming.rs
src/input.rs
src/number/streaming.rs

This reverts commit 6caa7b25372fa4a17a1ca599973014ea90d2b5df.
For now, #3 is looking like it causes more problems than its worth.  The Input into a complete/streaming specialized parser needs to be both, so splitting isn't offering any benefits.

Revert "fix!: Split InputTakeAtPosition into complete/partial traits"

---

benchmarks/benches/http.rs
src/_cookbook.rs
src/error.rs
src/lib.rs
src/parser.rs

It seems like the need for this is common enough to be worth having,
especially to drive correct behavior as this change highlights several
examples that ignored remaining input even when that isn't correct
(like in a `FromStr`).
This does add extra bounds for `FinishIResult`.  I had considered making
a separate extension trait but the likelihood it would be needed is low.
If anything, I could see adding an `InputIsEmpty` trait and moving it to
that as that would be more universal (could work on some iterators).  If
we really need it, we can split the traits (create a
`FinishErrIResult`).  Let's see what feedback we get.
To make room for this, we renamed the existing `finish` to `finish_err`.

feat: Add FinishIResult::finish to drop remaining input 

---

src/combinator/mod.rs
src/input.rs
src/multi/mod.rs
src/parser.rs

We had to copy/paste parser definitions like `length_data` into `length_value` because it requires passing moving a parser from the caller to the `length_data` but we return a `FnMut` instead of a `FnOnce`, allowing `length_value` to be called multiple times.
What we need is to implement `Parser` for `&mut impl Parser` but we can't until negative impl traits are a thing.  So instead, this adds a new combinator to wrap `&mut impl Parser` in a type that implements `Parser`.  The name isn't great but we can change it later once we get a better one.

refactor(multi): Reuse some length_data logic

---

README.md
examples/json.rs
examples/json_iterator.rs
examples/s_expression.rs
examples/string.rs
src/_cookbook.rs
src/_tutorial.rs
src/bytes/tests.rs
src/character/mod.rs
src/combinator/mod.rs
src/combinator/tests.rs
src/error.rs
src/input.rs
src/lib.rs
src/multi/mod.rs
src/multi/tests.rs
src/parser.rs
src/str.rs
tests/arithmetic.rs
tests/arithmetic_ast.rs
tests/css.rs
tests/custom_errors.rs
tests/float.rs
tests/ini.rs
tests/issues.rs
tests/json.rs
tests/mp4.rs
tests/reborrow_fold.rs

This is a followup to #37 and is working towards Geal/nom#1408
The criteria for moving parsers was if they were common enough and did not affect the grammar.  This way, the code structure can help highlight the grammar.  This means I left out `cut`.  While it mutates the error, like `complerte`, it does so in a way that affects parsing and it should be elevated (I think).  I'm still a little mixed on that one.
Highlights
- `consumed` -> `Parser::with_recognized`
- The problem is `recognize` and `consumed` parallel each other
but its not obvious by the name.   `combine` calls it
`recognize_with_value`.  `nom-supreme` takes the approach of
`Parser::with_recognized`.  I feel like that makes the intent clear.
The problem comes in that `with_recognized` implies an order …

feat: Move non-grammar combinators to `Parser`

---

src/combinator/mod.rs
src/multi/mod.rs
src/parser.rs

I already didn't like the name in https://github.com/epage/nom-experimental/pull/34 but I saw both `nom-supreme` and
`combine` us the `by_ref` name, so figured familiar is better.

fix(parser): Rename as_mut_parser to by_ref 

---

examples/s_expression.rs
src/_cookbook.rs
src/_tutorial.rs
src/bits/mod.rs
src/bits/tests.rs
src/combinator/mod.rs
src/lib.rs
src/multi/tests.rs
src/parser.rs
src/sequence/mod.rs
src/sequence/tests.rs
tests/css.rs
tests/ini.rs
tests/ini_str.rs
tests/issues.rs
tests/overflow.rs

More convenient syntax than `tuple((...))`
This was forked from Geal/nom#1425
- I deprecated `tuple()` rather than bothering to re-implement it in terms of `()`
- I didn't see a reason to add a `parse` combinator within this PR
Fixes Geal/nom#1417

feat(parser): impl Parser for tuples 

---

benchmarks/benches/arithmetic.rs
examples/json.rs
examples/json_iterator.rs
examples/s_expression.rs
examples/string.rs
src/_cookbook.rs
src/branch/mod.rs
src/bytes/complete.rs
src/bytes/mod.rs
src/bytes/streaming.rs
src/bytes/tests.rs
src/character/complete.rs
src/character/mod.rs
src/character/streaming.rs
src/character/tests.rs
src/combinator/mod.rs
src/input.rs
src/lib.rs
src/str.rs
tests/escaped.rs
tests/ini_str.rs
tests/issues.rs
tests/json.rs
tests/reborrow_fold.rs

Currently, nom tries to offer one of every type of API (bytes vs char, one of vs many of, list vs predicate)
This expands `FindToken` to at least reduce the "list vs predicate" option by expanding on "list" patterns to also include ranges, single tokens, predicates, or even compound patterns using tuples.  This allowed us to replace `is_a` with `take_while1`, `is_not` with `take_till1`, and `satisfy` with `one_of`.  `char` being replaced by `one_of` was split out into #45.
In a related fashion, we simplified the offerings by making some char-specific predicates char/byte agnostic, including `anychar` (as `any`), `one_of`, and `none_of`.
Fixes Geal/nom#1580

fix(bytes): Generalize byte/char APIs

---

examples/iterator.rs
examples/json.rs
examples/json_iterator.rs
examples/s_expression.rs
examples/string.rs
src/_cookbook.rs
src/_tutorial.rs
src/branch/mod.rs
src/bytes/mod.rs
src/bytes/tests.rs
src/character/mod.rs
src/character/tests.rs
src/combinator/mod.rs
src/error.rs
src/lib.rs
src/parser.rs
tests/arithmetic.rs
tests/arithmetic_ast.rs
tests/escaped.rs
tests/float.rs
tests/ini.rs
tests/ini_str.rs
tests/issues.rs
tests/json.rs
tests/reborrow_fold.rs

We now support
- `&str` and `&[u8]` as `tag` parsers
- `char` as a `char` parser and `u8` as a `one_of` parser
- u8 and char ranges as `one_of` parsers
This is to allow reducing noise and making more natural to write a parser.  The downside is when running into type inference issues.
The other downside is that this prevents us from moving `Parser` and `IResult` into a `-core` crate.  However, I would expected we'd need most of `nom::input` in that as well which would be harder to keep compatibility on I suspect.
Fixes Geal/nom#1417
Fixes Geal/nom#1408

feat(parser): impl Parsers for literals

---

src/combinator/mod.rs
src/combinator/tests.rs
src/parser.rs

Bringing in the `Parser` trait prevents using `Into::into` and
`Parser::into` as postfix.  One way to fix this is to rename
`Parser::into` but the only idea I had for doing so was to split it
which I think makes more sense.

fix(parser)!: Split Parser::into into Parser::output_into and Parser::err_into

---

examples/json.rs
src/error.rs
src/parser.rs
tests/issues.rs

An example of an error I regression in switching `toml_edit` from `nom` to `combine`:
```
---- expected: tests/fixtures/invalid/table-with-pound.stderr
+++ Actual
1    1 | TOML parse error at line 1, column 5
2    2 |   |
3    3 | 1 | [key#group]
4    4 |   |     ^
5      - Unexpected `#`
6      - Expected `.` or `]`
5 +
7    6 | While parsing a Table Header
```
While I might not expect `nom` to report expected content automatically (yet?), I want to be able to manually build up the pieces.  Part of this is storing more than just `context: &'static str`.  I could go off and create more related traits but a simpler route is just making context generic.  This allows users to create their own context enum with all of the variants each parser needs.
This was inspired by `nom-supreme` which …

feat(error)!: Make Context content generic

---

src/bytes/mod.rs
src/parser.rs

This reverts commit ca1f51f01ef28ed877bf11941575823726f45b82.
This falls into an uncanny valley where if you do a range, you likely want to do compounds of ranges which will get you parser sequencing rather than alternation.
This is a follow up to #47

Revert "feat(parser): impl Parser for range types"

---

src/lib.rs

This is an unusual elevation of a specific subset of parsers with
unclearly named `nom::complete` and `nom::streaming` modules and we are
now putting even more items in the root namespace as we move away from
complete/streaming.

fix(bits)!: Don't re-export in root namespace 

---

src/combinator/mod.rs
src/input.rs
src/parser.rs

There are two main crates that provide location support for nom
- `nom-locate`: wide adoption for long time
- `pori`: more recent, only really being used by one application
While `pori` is less mature, I think it iterates quite well on `nom-locate`; so let's break this down.
How to track location
- `pori`: tracks how much `input` has advanced
- `nom-locate`: same as above but also tracks the line number
- leave initial input unchanged and only change begin/end indices, doing unchecked slicing of the input to get the current input
- keep initial and current input and use offset
- keep start pointer from initial and current input
For now, I'm going with (initial, input) because it is relatively easy to implement and the bookkeeping costs are paid when doing location lookups.  The downside …

feat(input): Add span support

---

src/bits/mod.rs
src/error.rs
src/input.rs

fix(error)!: Move ErrorConvert to error module

---

src/input.rs
src/traits.rs

FindSubstring<&[u8]>: make use of `memchr::memmem`

---

src/multi/mod.rs

This change avoids reallocation while filling in the array. In my case this causes a ~20% perf increase.
See rust-bakery/nom#1462

length_count: use Vec::with_capacity

---

src/bits/mod.rs

Add example for bits:::tag 

---

src/_cookbook.rs

See rust-bakery/nom#1334.  While not all parts of the PR description are clear to me, the old example is a lot more complicated, encouraging slower practices.

doc(recipes/identifier): convert to greedy parser

---

src/bits/complete.rs
src/bits/mod.rs
src/bits/streaming.rs
src/branch/mod.rs
src/bytes/complete.rs
src/bytes/mod.rs
src/bytes/streaming.rs
src/character/complete.rs
src/character/mod.rs
src/character/streaming.rs
src/character/tests.rs
src/combinator/mod.rs
src/error.rs
src/input.rs
src/multi/mod.rs
src/number/complete.rs
src/number/mod.rs
src/number/streaming.rs
src/parser.rs
src/sequence/mod.rs

Trying to separate this from the trait merger that mirrors rust-bakery/nom#1612 so its easier to talk about both.
In general
- Clarifies what types are input types
- This highlighted that `ContainsToken` (formerly `FindTokens`) is actually a token type
- **There are still some types being treated as input that aren't properly input**
- Clarifies terminology
- `Offset::offset` has confused me as which value goes where, so using `Offset::offset_to`
- winnow-rs#93 is an example of the problem with "index", "position", and "offset" being used interchangeably
- Makes generic parameters more consistent

fix(input)!: Cleanup to prepare for trait merger

---

src/combinator/mod.rs
src/parser.rs

Unsure how to handle `O: From<u8>` type bounds.
Inspired by rust-bakery/nom#1460

fix: Prefer Into over From in bounds

---

src/input.rs

This does not help with `Compare` (because of ignore case) and `FindSlice` (`memchr`).
Inspired by rust-bakery/nom#1482

feat(input): Blankt impl for all slices

---

src/combinator/mod.rs
src/combinator/tests.rs

We have enough ways of doing this, we should consolidate down.

fix(comb): Deprecate `all_consuming`

---

src/_cookbook.rs
src/combinator/mod.rs
src/parser.rs

Inspired by rust-bakery/nom#1537, rust-bakery/nom#1223

feat(parser): Add `Parser::void`

---

src/lib.rs

Our core/alloc/std abstrcaction is incomplete, so there is limited value in people relying on it.
It clutters the documentation.
For me, this feels more like an artifact of the prior macro design.
Gone.

fix!: Remove `lib` from the pub API

---

examples/ini/parser.rs
examples/ini/parser_str.rs
examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_streaming.rs
examples/json_iterator.rs
src/_cookbook.rs
src/bytes/complete.rs
src/bytes/streaming.rs
src/character/mod.rs
src/input.rs
src/lib.rs
src/multi/mod.rs
src/multi/tests.rs
tests/testsuite/fnmut.rs
tests/testsuite/issues.rs
tests/testsuite/utf8.rs

I went with a custom trait so we could cover `()` and `usize` as well as
support custom capacities.
This comes at the cost of supporting any container possible.  We could
possibly do that with a `Extendable(T: Default + Extend)` newtype.
As an alternative to `()` and `usize` is GATs.  The main difference is
who drives the types.
This allowed us to deprecate `many[01]_count`.
Along the way, we also updated `escaped_transform` to this so we use this consistently.  This exposed why #19 was broken.  `ExtendInto` was implemented both for input and for outputs for the two parsers, which was meant to include `char`.  The backward design of  the trait made this less obvious what was happening which I feel is a win for the new trait design.
However, now that `Accumulate` has no `input` connection, …

feat(multi): Switch from Vec to impl Accumulate 

---

src/bytes/complete.rs
src/bytes/streaming.rs
src/bytes/tests.rs

Fixes #93
BREAKING CHANGE: `take_while_m_n` now errors if `n < m`

fix(bytes)!: Ensure take_while_m_n handles UTF-8 correctly

---

src/character/complete.rs
src/character/mod.rs
src/character/streaming.rs
src/input.rs
src/number/complete.rs
src/number/streaming.rs

This will turn panics into compile errors and open the way for some unsafe for #115

fix(input)!: Prevent `str` from being processed as arbitrary bytes

---

src/input.rs

- If its trivial wrapper, always inline
- Otherwise, let the compiler decide

fix(input): Normalize `inline`

---

src/error.rs
src/multi/mod.rs
src/multi/tests.rs
src/stream/mod.rs

This helps improve the debug experience  (#102) while avoiding panic code being generated in release builds and gives end-users control over what is happening
BREAKING CHANGE: Some parsers now return `ErrorKind::Assert` rather than parser-specific `ErrorKind`s

fix(multi)!: Panic at the infinite loop

---

examples/json/bench.rs

Inspired by rust-bakery/nom/#1639

bench(json): Include `VerboseError`

---

src/_tutorial.rs
src/bits/mod.rs
src/bytes/mod.rs
src/combinator/mod.rs
src/error.rs
tests/testsuite/issues.rs

This gives us more implementation freedom

fix!: Consistently be `FnMut` parsers

---

.clippy.toml
.github/workflows/ci.yml
Cargo.toml

This was needed to use one of our dependencies in https://github.com/winnow-rs/winnow/pull/156

chore: Bump MSRV to 1.56.0 

---

.clippy.toml
.github/workflows/ci.yml
Cargo.toml

I really want string interpolation for `format!` which came in 1.58 for #156.  I went to 1.60 since that is a nice round number that I've previously bumped a lot of projects to and it is almost a year old, so its still relatively conservative.

chore: Bump MSRV to 1.60.0

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml
Cargo.lock
Cargo.toml
src/bits/mod.rs
src/branch/mod.rs
src/bytes/mod.rs
src/character/mod.rs
src/combinator/mod.rs
src/lib.rs
src/macros.rs
src/multi/mod.rs
src/number/mod.rs
src/sequence/mod.rs
src/trace/internals.rs
src/trace/mod.rs

This will report what a parser has done for easier debugging.
I really hoped to have the success path highlight what of the input was
captured but
- That gets messy when the `input_width` isn't wide enough
- That gets messy when the data we are consuming is in terms of the
original input but we are manipulating the debug output
Example output:
Fixes #102

feat(trace): New `trace` combinator

---

src/bits/mod.rs
src/bytes/mod.rs
src/character/mod.rs
src/number/mod.rs
src/stream/mod.rs

This will be cleaned up a lot and reduce duplicate code with #97
In doing this, I removed the compile-time conversion.  We weren't using it, providing examples for it, etc and it complicated things around error reporting as it was a distinct input type.

feat(stream)!: Allow runtime selection of the partial/complete

---

src/combinator/mod.rs
src/error.rs
src/multi/mod.rs
src/parser.rs
src/stream/mod.rs
tests/testsuite/issues.rs

This matches `backtrack_err` and `cut_err`

fix!: Clarify `Parser::complete_err` is error related

---

src/stream/mod.rs

fix(stream): Pass on inner stream's runtime state

---

benches/number.rs
examples/json/parser_partial.rs
examples/json_iterator.rs
src/bits/mod.rs
src/bytes/mod.rs
src/bytes/tests.rs
src/character/mod.rs
src/character/tests.rs
src/combinator/tests.rs
src/error.rs
src/multi/mod.rs
src/number/mod.rs
src/parser.rs
src/stream/mod.rs
tests/testsuite/issues.rs

If you used `Partial`, you couldn't use `"hello"` as a tag but had to do
`tag("hello")` because we needed to constrain the generic parameter.
Now that we've removed it, literals can be used as desired.
The downside is that for `FinishIResult`, this shifts an error from
compile time to runtime.  At least with `is_partial_support`, the user
is more likely to see it than they would have with the original `nom`
code.
BREAKING CHANGE: `StreamIsPartial` no longer takes a `const PARTIAL:
bool` generic parameter.  This was replaced with `is_partial_support`
function.
Fixes #79

fix(parser)!: Allow literals to be parsers of partial inputs

---

examples/http/parser_streaming.rs
examples/json/bench.rs
examples/json/parser_partial.rs
src/bits/tests.rs
src/branch/tests.rs
src/bytes/mod.rs
src/bytes/streaming.rs
src/bytes/tests.rs
src/character/mod.rs
src/character/tests.rs
src/combinator/mod.rs
src/combinator/tests.rs
src/lib.rs
src/multi/mod.rs
src/multi/tests.rs
src/number/mod.rs
src/number/tests.rs
src/parser.rs
src/sequence/tests.rs
src/stream/mod.rs
tests/testsuite/issues.rs
tests/testsuite/overflow.rs
tests/testsuite/utf8.rs

Under the original `nom` design, users could mix and match complete/streaming parsers as needed.  Now, they can't.  This restores that ability by modifying the stream.  As part of that, we apply this to two existing parsers, `length_value` and `Parser::and_then`
The problem is this comes with a 30% performance hit for partial parsing because we increased the size of the Stream (I benchmarked with `is_partial` returning a static value and no change).  See #72 for fixing that.
Despite the performance degradation, I'm going to merge this as this is necessary functionality for parsers to work correctly and we have #72 for improving the performance.

fix!: Parsing over a slice should invoke complete parsers

---

src/bits/mod.rs
src/multi/mod.rs
src/stream/mod.rs

In testing out the new API, I found the custom slice types to be too much to deal with.

fix(stream)!: Debug types use native slice types

---

Cargo.toml
src/stream/mod.rs

This doesn't benefit every parser, so let's not make every parser pay the cost.

fix: Make memchr an optional dependency

---

src/combinator/mod.rs
src/combinator/tests.rs

So `Parser::flat_map` had the right bound but not the `Parser` impl for `FlatMap`.  Changing the bound should not be a breaking change.
Fixes #195

fix(comb): Relax flat_map's trait bound

---

Cargo.toml
src/lib.rs
src/stream/mod.rs

The crate (`master` branch) does not compile with nostd.
1. Run `cargo check --no-default-features` and/or `cargo test --no-default-features`.
2. Run `cargo check --no-default-features --features=alloc` and/or `cargo test --no-default-features --features=alloc`.
Both `check` and `test` pass even when `std` feature is disabled.
`check` and `test` fail when `std` feature is disabled.

fix: Make things compilable without std nor alloc

---

src/error.rs

> Err is clonable, but error::Error was not.
cherry-picked from rust-bakery/nom#1650
- Expanded to include `Copy`
- Note that `VerboseError` already supports `Clone`

Make Error clonable

---

src/character/mod.rs
src/character/tests.rs

rust-bakery/nom#958 required at least one non-escaped value but only for `complete` and  not for `streaming`.  There was also no explanation of use case or discussion.  Generally, escaping is used for strings and strings are generally allowed to be empty.
There is the question of whether it should be renamed to `escape0`.  I'm setting that aside for  now.

fix(char)!: Allow empty `escape`

---

examples/arithmetic/main.rs
examples/css/main.rs
examples/css/parser.rs
examples/ini/main.rs
examples/json/main.rs
examples/string/main.rs
src/_tutorial/chapter_6.rs
src/_tutorial/chapter_7.rs
src/error.rs
src/lib.rs
src/parser.rs
src/stream/mod.rs

This was made possible be renaming `Parser::parse` to `Parser::parse_next`
Fixes #80

feat: Replace `FinishIResult::finish` with `Parser::parse`

---

benches/contains_token.rs
src/character/mod.rs
src/stream/mod.rs

Updates #223. This brings the peformance of the space parsers back to pre-0.4.0 levels.  The root cause is not clear and the performance
difference shown does not align with the `contains_token` benchmark.
This only fixes half of the performance regression from https://github.com/winnow-rs/winnow/pull/210 though. There are still some other changes that negatively affect performance which I didn't figure out yet.

perf: Undo performance regression from 0.4.0

---

src/_topic/mod.rs

Our recent discussion in https://github.com/winnow-rs/winnow/issues/223 pushed me to finally make the initial release of `hcl-edit` which I've been holding of for too long already since I got carried away with missing details.
The crate is far from complete, but the parser implementation is functional and actually quite fast.
So I figured I'll add it to the list of parsers for others to explore real-world uses of winnow.
I hope this does not scare away people from winnow since HCL is quite a big and messy piece to parse, given the three sub-languages it has and some other quirks like the absense of keywords (for example, `true` can be an identifier or a boolean, depending on the context) :wink:.

docs: Add `hcl-edit` to the list of parsers using `winnow`

---

.clippy.toml
.github/workflows/ci.yml
Cargo.toml
examples/css/parser.rs
examples/string/parser.rs
src/_topic/language.rs
src/bytes.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/tests.rs
src/lib.rs
src/multi.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
src/trace/mod.rs
tests/testsuite/issues.rs
tests/testsuite/overflow.rs

This hits the highest priorities among #98.
Unlike rust-bakery/nom#1608 which created a `NomRange` trait and generalized the functions based on that, we mirrored the `StreamingIsPartial` approach and normalize the ranges in `#[inline(always)]` code dispatch to the optimized variants.  This means the user only pays for up to 3 implementations rather than paying for an implementation per range type.
This is also taking a conservative approach and not touching the existing `0` or `1` suffixed functions.  No benchmarks touch what we changed

fix: Generalize `_m_n` variants into ranges

---

src/ascii/mod.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/token/mod.rs

Tried this before in #213 but it slowed down the complete cases (but
sped up the partial cases).
Not fully sure what happened before but I figured that by using
const-generics, we can effectively get the old behavior while having one
textual version of the function.  The compiler will effectively generate
the alternative version of the function for us and which ever isn't used
gets dropped.
Looks like this was successful too, maintaining performance where we
previously lost it and getting the performance gains of merging:
```
json/basic/canada       time:   [12.850 ms 12.941 ms 13.036 ms]
thrpt:  [164.68 MiB/s 165.89 MiB/s 167.06 MiB/s]
change:
time:   [+0.9086% +1.7638% +2.6956%] (p = 0.00 < 0.05)
thrpt:  [-2.6248% -1.7332% -0.9004%]
Change within noise threshold.
json/verbose/canada …
```

refactor: Merge partial/complete implementations

---

src/parser.rs
src/stream/mod.rs
src/token/mod.rs
src/trace/mod.rs

#247 consolidated some of the parsers as suggested in #98 but there was a report of a slowdown from this change.
While this PR makes several changes, the core improvement is adding `#[inline(always)]` to the `Parser::parse_next` impls that we provide for users.  I assume that created a barrier in the compiler so it couldn't optimize out the overhead from `take_while`s dispatching.  Somehow this only made a big difference with the `ascii::` parsers and not from direct uses of `take_while`.
- winnow 0.4.4 for parse/hcl-edit/deeply_nested.tf: 15.235 µs
- winnow 0.4.6 for parse/hcl-edit/deeply_nested.tf: 18.273 µs
- winnow 0.4.4 for parse/hcl-edit/deeply_nested.tf: 14.513 µs

perf(parser): Restore pre-consolidation performance

---

benches/contains_token.rs
examples/arithmetic/parser.rs
examples/ini/parser_str.rs
examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
examples/json_iterator.rs
examples/ndjson/parser.rs
examples/s_expression/parser.rs
examples/string/parser.rs
src/_topic/language.rs
src/_tutorial/chapter_2.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/combinator/core.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/reborrow_fold.rs
tests/testsuite/utf8.rs

`&str` is convenient but
- It reads oddly, lookling like they are sequenced
- No good way to warn people about the performance without just removing
it
Re-measured to performance to be sure:
```
contains_token/str/canada
time:   [15.830 ms 15.851 ms 15.874 ms]
thrpt:  [135.24 MiB/s 135.44 MiB/s 135.61 MiB/s]
contains_token/slice/canada
time:   [2.1956 ms 2.2033 ms 2.2111 ms]
thrpt:  [970.92 MiB/s 974.35 MiB/s 977.76 MiB/s]
```
All other impls are in the ballpark of `slice`
Fixes #226

perf!: Prevent use of slow `str.contains_token`

---

src/ascii/mod.rs

This is mostly cleanup found when working on checkpointing in prep for mutable input

fix(ascii): Allow escaped_transform on core

---

src/error.rs

fix(error)!: Clarify convert_error is meant to be used with streams

---

src/ascii/mod.rs
src/ascii/tests.rs

This was identified in nom in rust-bakery/nom#1673

fix(ascii): Correctly parse 'infinity' 

---

src/error.rs
src/parser.rs

Until we figure out `Parser::parse`, this is helpful.  It is likely helpful anyways.

fix(error): Expose ErrMode::into_inner

---

proptest-regressions/stream/tests.txt
src/ascii/mod.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/combinator/core.rs
src/combinator/parser.rs
src/combinator/tests.rs
src/parser.rs
src/stream/mod.rs
src/stream/tests.rs
src/token/mod.rs
src/trace/internals.rs

This is a step towards #72
v0.4.7
```
json/basic/canada       time:   [10.272 ms 10.308 ms 10.347 ms]
thrpt:  [207.47 MiB/s 208.26 MiB/s 208.98 MiB/s]
json/verbose/canada     time:   [32.539 ms 32.714 ms 32.893 ms]
thrpt:  [65.264 MiB/s 65.622 MiB/s 65.975 MiB/s]
json/dispatch/canada    time:   [8.9747 ms 8.9926 ms 9.0118 ms]
thrpt:  [238.22 MiB/s 238.73 MiB/s 239.20 MiB/s]
json/streaming/canada   time:   [10.612 ms 10.667 ms 10.726 ms]
thrpt:  [200.14 MiB/s 201.25 MiB/s 202.29 MiB/s]
```
main (6747a8d6)
```
json/basic/canada       time:   [10.234 ms 10.254 ms 10.274 ms]
thrpt:  [208.94 MiB/s 209.37 MiB/s 209.76 MiB/s]
json/unit/canada        time:   [9.5594 ms 9.5917 ms 9.6248 ms]
thrpt:  [223.04 MiB/s 223.82 MiB/s 224.57 MiB/s]
json/verbose/canada     time:   [30.371 ms 30.442 ms 30.517 …
```

feat(stream)!: Allow mutable iteration

---

benches/number.rs
examples/http/parser.rs
examples/http/parser_streaming.rs
examples/ini/parser_str.rs
examples/json_iterator.rs
src/ascii/tests.rs
src/binary/bits/tests.rs
src/binary/tests.rs
src/combinator/core.rs
src/combinator/tests.rs
src/token/tests.rs
tests/testsuite/issues.rs
tests/testsuite/multiline.rs
tests/testsuite/reborrow_fold.rs

This is a step towards #72
v0.4.7
```
json/basic/canada       time:   [10.272 ms 10.308 ms 10.347 ms]
json/verbose/canada     time:   [32.539 ms 32.714 ms 32.893 ms]
json/dispatch/canada    time:   [8.9747 ms 8.9926 ms 9.0118 ms]
json/streaming/canada   time:   [10.612 ms 10.667 ms 10.726 ms]
```
#276
```
json/basic/canada       time:   [10.226 ms 10.241 ms 10.256 ms]
json/unit/canada        time:   [8.6800 ms 8.7021 ms 8.7269 ms]
json/verbose/canada     time:   [30.948 ms 30.991 ms 31.037 ms]
json/dispatch/canada    time:   [8.5036 ms 8.5273 ms 8.5542 ms]
json/streaming/canada   time:   [10.727 ms 10.753 ms 10.781 ms]
```
#277
```
json/basic/canada       time:   [9.6649 ms 9.6840 ms 9.7037 ms]
json/unit/canada        time:   [9.0364 ms 9.0944 ms 9.1513 ms]
json/verbose/canada     time: …
```

refactor(test): Rely on trait, rather than direct calls

---

src/error.rs

This is to help the transition to 0.5 which has #282

feat(error): Backport additional names for items

---

src/stream/mod.rs
src/trace/internals.rs

BREAKING CHANGE: `Stream::raw` is a new required function

fix(trace)!: Fancy rendering for BStr / Bytes

---

src/_tutorial/chapter_2.rs
src/_tutorial/chapter_3.rs
src/_tutorial/chapter_4.rs
src/_tutorial/chapter_5.rs
src/_tutorial/chapter_6.rs
src/_tutorial/chapter_7.rs
src/ascii/mod.rs

This is bigger than just changing the types.  This tries to explain more
underlying details so people are better able to handle more complex
problems they face, like `toml_edit` building up strings using a fast
path then a slow path without `alt`.

docs(tutorial): Update for new API

---

CHANGELOG.md
benches/number.rs
examples/custom_error.rs
fuzz/fuzz_targets/fuzz_arithmetic.rs
src/_tutorial/chapter_2.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/binary/tests.rs
src/combinator/branch.rs
src/combinator/core.rs
src/combinator/multi.rs
src/combinator/parser.rs
src/combinator/tests.rs
src/error.rs
src/parser.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/custom_errors.rs

`Stream` no longer is required to be `Sized` and, in theory, should be object safe.
This also had the benefit of finding bugs in `escape` and `escape_transform` as well as cleaning up that code.

fiix(stream)!: Relax super traits for `Stream`

---

src/ascii/mod.rs
src/ascii/tests.rs
src/parser.rs
src/token/mod.rs

This was inspired by #232.  I tried to remove the `Clone` bound completely but was running into compiler issues that were non-obvious.  The worst part is that inputs with costlier `Stream::Token::clone` calls will be in the inner-loop for `Stream::offset_for` for parers like `take_while`.

fix: Loosen `Clone` bound for tokens to `Copy`

---

src/error.rs

Found this useful within cargo-smart-release where the extra details aren't needed

feat(error): Add ParseError::into_error

---

src/combinator/branch.rs
src/combinator/tests.rs

Now that min-const-generics is stabilized, it's possible to (backwards-compatibly) write a version of `alt` that uses a const array as input instead of being limited to only tuples - this allows us to lift the 21-element limitation on tuples passed to `alt`.
Upstream: rust-bakery/nom#1556

feat(comb): Allow arrays as input to `alt`

---

src/combinator/parser.rs
src/error.rs

Found this useful for gitoxide

feat(error): Impl AddContext for ErrMode

---

Cargo.lock
Cargo.toml
src/trace/internals.rs

Noticed through `cargo-deny` that I have several duplicate dependencies. So I went ahead and updated
all to their latest version. Most notably is the updat of `anstyle` to the 1.0 release and replacing `anstyle-stream` with `anstream` (which seems to be a rename of the crate).

Update dependencies to their latest version

---

src/error.rs

gix was using `VerboseError` with a converted input type to easily dump parse state in tests for easier debugging.
This seemed like a nifty enough of an idea that I generalized it, building on ideas from `nom-supreme`

feat(error): `TreeError` to trace full error path

---

src/binary/bits/mod.rs

It's not a big deal and compiler should be able to do this automatically, but this also reduces the scope of the definition.
See rust-bakery/nom#1683

refactor(binary): Move var definition close to use

---

src/error.rs

Found this when comparing changes in Byron/gitoxide#956

perf(error): Lower ErrMode's overhead

---

src/stream/mod.rs

This reverts commit 489aa2ace0ce77790cf8d2aa3fc0fcf8a8f7ccb2.
PR #86 "FindSubstring<&[u8]>: make use of `memchr::memmem`"
When testing under gitoxide, it turned out this slowed down gitoxide-specific micro-benchmarks from ~170ns to ~240ns

perf(token): Speed up `take_until` under simd

---

src/stream/mod.rs
src/trace/mod.rs

I've seen a few typos browsing the docs. I've seen more, but those are the one I can find right now.

Fix minor typos

---

src/stream/mod.rs

Follow-up from https://github.com/winnow-rs/winnow/discussions/330 to document the fact that `winnow` considers converting from span byte offsets to line numbers out of scope.

Note that winnow doesn't provide byte-to-line-number conversions

---

src/stream/mod.rs
src/stream/tests.rs

fix(stream): Correctly count offsets for non-byte slices 

---

src/error.rs
src/stream/mod.rs

In particular, this calls out a problem when you conflate the two.
Fixes #341

docs: Be explicit on offset vs index

---

src/combinator/mod.rs

Update the list of parsers and combinators to the new mutable input and `PResult` from #278.
Note, this was just dumb copy and paste. I didn't verify if it is correct.

docs: fix list of parsers and combinators

---

src/ascii/mod.rs

fix: Deprecate signed Uint impls

---

Cargo.lock
Cargo.toml
src/stream/mod.rs
src/stream/tests.rs

Currently Accumulate is only implemented for HashMap<K, V, RandomState>.
This generalizes the Accumulate impl to HashMap<K, V, S: BuildHasher + Default>.
See #356

Impl Accumulate for more HashMaps

---

examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
examples/json_iterator.rs
examples/ndjson/parser.rs
src/_tutorial/chapter_5.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/tests.rs
src/stream/tests.rs
tests/testsuite/issues.rs

This attempts to add a `separated` parser that accepts a range similar to `repeat`.
Towards #98.
I tried to copy as much logic as possible from existing code. I'm unfamiliar with the code and may have missed some things, e.g. checkpoint resets, infinite loop checks, or correct error types. Please double check carefully and feel free to edit if it can be improved.

feat(combinator): add separated

---

src/combinator/multi.rs

Document infinite loop check in separator parser of `separated`.

docs(combinator): infinite loop check in separated

---

src/combinator/multi.rs

The combination `separated` takes a range, not separate m and n arguments. Fix the documentation.

docs: Separated takes a range, not separate m and n arguments

---

src/ascii/mod.rs
src/combinator/mod.rs
src/parser.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/utf8.rs

feat(token): Add Caseless for tags 

---

Cargo.toml
benches/find_slice.rs
src/stream/mod.rs

Before/after (with simd)
```
find_slice/byte/empty   time:   [8.6164 ns 9.0722 ns 9.5994 ns]
change: [-43.031% -39.731% -35.814%] (p = 0.00 < 0.05)
Performance has improved.
find_slice/slice/empty  time:   [8.9148 ns 9.4395 ns 9.9990 ns]
change: [-40.889% -36.871% -32.492%] (p = 0.00 < 0.05)
Performance has improved.
find_slice/byte/start   time:   [349.03 ns 382.08 ns 418.18 ns]
change: [-66.578% -63.083% -59.659%] (p = 0.00 < 0.05)
Performance has improved.
find_slice/slice/start  time:   [621.33 ns 662.95 ns 707.40 ns]
change: [-55.891% -51.971% -47.614%] (p = 0.00 < 0.05)
Performance has improved.
find_slice/byte/medium  time:   [535.01 ns 560.18 ns 586.97 ns]
change: [-68.347% -65.802% -62.864%] (p = 0.00 < 0.05)
Performance has improved.
find_slice/slice/medium time:   [681.00 ns …
```

perf(token): Speed up 'take_until' for str/char 

---

src/stream/mod.rs

Allows combinators such as `repeat` and `separated` to collect single items into a `HashSet` or `BTreeSet` similar how `(K, V)` tuples can already be collected into a `HashMap` and `BTreeMap`.
Fixes #376

feat(stream): Accumulate into BtreeSet and HashSet

---

src/combinator/multi.rs
src/combinator/parser.rs
src/parser.rs

We inherited this inconsistency from nom
This still leaves out for token predicates but I think that should be fine.
See #392 for discussion on this.

fix: Allow FnMut for parser predicates

---

src/_topic/why.rs
src/binary/mod.rs
src/binary/tests.rs
src/token/tests.rs
tests/testsuite/issues.rs
tests/testsuite/overflow.rs

fix(binary): Clarify TLV parser names

---

examples/css/parser.rs
examples/http/parser.rs
examples/http/parser_streaming.rs
src/combinator/mod.rs
src/combinator/sequence.rs
src/macros/mod.rs
src/macros/seq.rs
src/macros/test.rs

feat(seq): 'seq' macro for easier skipping

---

src/token/mod.rs

Not entirely clear if its needed in this case but I generally have found that these const conditionals seem to provide more optimized results.
I did a `rg is_partial_support -A 4` to see if any others had this problem and this seemed to be isolated.
Fixes #404

perf(token): Allow optimizer remove branch

---

src/ascii/mod.rs
src/ascii/tests.rs

Fixes `winnow::ascii::float` not matching any variants of `inf`/`infinite` prefixed by a `+`/`-` sign as mentioned in https://github.com/winnow-rs/winnow/issues/411.

Fixes `winnow::ascii::float` not matching `+inf` or `-inf`

---

src/stream/mod.rs

I think this is a holdover from when we were more clone happy with streams.

fix(stream): Don't require Clone for Stateful's State

---

src/combinator/mod.rs

At the moment in [the docs about `combinator` module](https://docs.rs/winnow/latest/winnow/combinator/index.html) the entry for `dec_int` points to the page for  `dec_uint`. This small PR fixes that.
I'm not sure if it worth creating an issue for change so small, so I didn't create it 🙂

Fix link to `dec_int` in the docs

---

examples/http/parser.rs
examples/http/parser_streaming.rs
examples/ini/parser_str.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/combinator/mod.rs
tests/testsuite/issues.rs

The `not_*` naming schema is confusing that its "all characters up to".
My hope is this rename will clarify that.  I left out `take` for
brevity.

fix(ascii): Clarify till_line_ending is take_till 

---

examples/json/parser_dispatch.rs
src/_tutorial/chapter_3.rs
src/combinator/core.rs
src/macros/dispatch.rs
src/macros/seq.rs
src/macros/test.rs
src/parser.rs

fix(comb): Deprecate `success` in favor of `empty`

---

src/stream/mod.rs

Fixes #444
BREAKING CHANGE: This adds an extra generic parameter to `Checkpoint<T, S>`

fix(stream)!: Limit Checkpoints to their stream type

---

src/stream/mod.rs
src/token/tests.rs

In a way, this is split out of #428.  This is prep for `AsciiChar`

feat(token): Allow a byte to pass to tag

---

benches/next_slice.rs
examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
examples/json_iterator.rs
examples/ndjson/parser.rs
src/_topic/language.rs
src/_topic/stream.rs
src/_tutorial/chapter_2.rs
src/_tutorial/chapter_3.rs
src/ascii/mod.rs
src/binary/bits/mod.rs
src/binary/bits/tests.rs
src/binary/mod.rs
src/combinator/core.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/sequence.rs
src/combinator/tests.rs
src/parser.rs
src/stream/mod.rs
src/stream/tests.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/issues.rs
tests/testsuite/utf8.rs

`tag` refers to specific patterns in binary parsing (tag-length-value encoding).  `literal` and `pattern` are a bit more universally applicable.

fix: Rename `tag` parsers to `literal` and `pattern`

---

src/stream/mod.rs

perf(stream): Ensure u8::slice_len is inlined

---

assets/trace.svg
src/ascii/mod.rs
src/combinator/branch.rs
src/parser.rs
src/token/tests.rs

Originally, this was going to be done for performance reasons but when
comparing this to the previous commit, `tag(char)` / `char` slowed down
dramatically in the `next_slice` benchmark.
However, `json` benchmark was unchanged.  This also (slightly)
simplifies traces, is more direct in what it says, and does still speed
things up for UTF-8-exclusive `char`s, so going forward with it.
Fixes #418
Fixes #427
BREAKING CHANGE: `char` parers now always return `char` as the output
and now require `I: Compare<char>`
BREAKING CHANGE: `u8` parers now  require `I: Compare<u8>`

fix(parser): Switch literal impl's from `one_of` to `literal`

---

src/combinator/mod.rs

Remove reference to `take_till1` deprecated in #450.
Not sure, if the following sentence also needs to be updated or is still correct?
> `take_till(f)` is equivalent to `take_while(0.., \|c\| !f(c))`

fix(docs): fix `take_till`

---

src/combinator/mod.rs

Remove reference to `success` deprecated in #440.

docs: Update reference from `success` to `empty`

---

examples/custom_error.rs
src/_tutorial/chapter_3.rs
src/ascii/mod.rs
src/binary/bits/mod.rs
src/combinator/branch.rs
src/combinator/core.rs
src/combinator/multi.rs
src/combinator/parser.rs
src/combinator/tests.rs
src/error.rs
src/parser.rs
src/stream/mod.rs
tests/testsuite/custom_errors.rs

fix(error)!: Consistently pass Checkpoints around

---

src/_tutorial/chapter_0.rs
src/_tutorial/chapter_1.rs
src/_tutorial/chapter_2.rs
src/_tutorial/chapter_3.rs
src/ascii/mod.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/combinator/branch.rs
src/combinator/core.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/sequence.rs
src/stream/mod.rs
src/token/mod.rs

Feedback
> And every time the docs say "this is simple" or "this is easy" etc., it's really discouraging if you are struggling to understand.
"simple" is meant to convey "basic".  To avoid the mismatch between the language and people's potential experience, I've tried to find other words.
> One example is take_till vs take_until. Semantically that means the same thing, and their descriptions on the doc's list of combinators, seem to say the same thing just with different words.
The naming has always bothered me but I still don't have a better idea.   We can at least cross-reference and clarify the distinctions
> Another is the phrase "the longest list of bytes/chars"; it feels ambiguous. Is there a chance it'll return some kind of shorter list? "longest" is a comparison, but it's not …

docs: Try to clear up some confusion

---

src/ascii/mod.rs
src/binary/bits/mod.rs
src/combinator/core.rs
src/stream/mod.rs
src/token/mod.rs

Trying to balance documentation-overload with helping new users who might be uncomfortable with the generics.  Was a bit hesitant if this met that balance but my [mastadon poll](https://hachyderm.io/@epage/112015792862307396) seemed to be in favor.
- Didn't do this to parsers like `opt` or `repeat` where there is nothing concrete to work with
- Skipped `binary` because that is a lot of repetition that I didn't want to take on atm

docs: Give example of a non-generic signature

---

src/error.rs

Quick fix for #498
I didn't touch TreeError because I couldn't see a particularly easy way of converting input types on it other than rewriting the entire tree which seemed a bit over the top.
I added the `InputError` -> `ContextError` conversion because I could rather than because I needed it, I can remove it if you don't want it.

Add impl `ErrorConvert` for `ContextError`

---

src/_tutorial/chapter_8.rs

While trying to run tests with the debug feature using the tutorial's command, I encountered an error:
```bash
$ cargo test --features debug
error: none of the selected packages contains these features: debug
```
After some investigation and learning how features in cargo work, I found that using `cargo test --features winnow/debug` resolved the issue. I recommend updating the tutorial to include this command to avoid future confusion for other users.

Update command in chapter 8

---

src/ascii/mod.rs

No issue because obvious bug: "zero or more" should be "one or more" for the `space1` combinator.

Fix documentation for space1 combinator

---

src/combinator/branch.rs
src/combinator/tests.rs

This mirrors rust-bakery/nom#1754

feat(comb): Allow 'alt' on array refs

---

src/stream/mod.rs

Signed-off-by: TennyZhuang <zty0826@gmail.com>
Resolve #524

feat: derive Default for (Stateful|Recoverable)

---

src/binary/bits/mod.rs
src/binary/mod.rs

The `AsBytes` bounds came about because
- I prefer composing parsers where possible
- `Stream::Slice` is not guaranteed to be a `Stream` and making it so is messy
This change came about because of winnow-rs/winnow#528

fix: Remove AsBytes from some trait bounds

---

src/_tutorial/chapter_8.rs

This prevents the large image from appearing inline in the last line of
the paragraph.
Without this fix:

doc: Add a blank line between paragraph and image

---

src/binary/tests.rs

Pulled from rust-bakery/nom#1769
I skipped the float ones because I didn't feel like adapting them to the `binary` mod.

test(binary): Cover more cases

---

src/parser.rs
src/stream/mod.rs

This isn't needed with the new `&mut I` API as of 0.5

docs(stream): Remove Stateful's use of cell 

---

examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
examples/ndjson/parser.rs
src/_topic/language.rs
src/_tutorial/chapter_5.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/combinator/branch.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/parser.rs
src/parser.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/float.rs
tests/testsuite/utf8.rs

We can consider other names, like `capture`, in the future but for now, let's be consistent.
Fixes #488

fix: Rename `recognize` to `take` for consistency 

---

src/binary/bits/tests.rs
src/error.rs

fix(partial): Clarify Needed::Size is for offset, not tokens

---

src/combinator/mod.rs

The pipes were interpreted as column delimiters. Also, I had to use `<code></code>` instead of backticks to have the pipes display as `|` instead of `\|` in the docs.

fix(docs): Escape pipes in `Repeat::fold` usage

---

src/stream/mod.rs

Inspired by #593 which is trying to use `winnow` for HDF5

feat(stream): Allow reseting streams to an absolute position

---

Cargo.lock
Cargo.toml

This removes one of the uses of `windows-sys` 0.48 and rustix 0.37 (but others remain).
It adds `windows-sys` 0.59, but both 0.52 and 0.59 depend on the same version of `windows-targets.

deps: Update `terminal_size` to 0.4.0

---

.github/workflows/audit.yml
.github/workflows/pre-commit.yml
CONTRIBUTING.md
fuzz/fuzz_targets/fuzz_arithmetic.rs

chore: Update from _rust template

---

src/combinator/multi.rs

Adjust `Repeat::fold` doc parameter name to match that of implementation.

Adjust `Repeat::fold` doc parameter name to that of implementation

---

Cargo.toml

You can see this feature in action on all dtolnay's crates or on mine (like `sysinfo`).

Enable `--generate-link-to-definition` rustdoc option on docs.rs

---

src/_topic/why.rs
src/_tutorial/chapter_3.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/combinator/core.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/error.rs
src/stream/mod.rs
src/token/mod.rs

docs: Highlight notes/warnings in a block

---

src/combinator/core.rs
src/parser.rs

docs: Clarify peek's behavior with Input

---

src/_tutorial/chapter_5.rs

While going through the tutorial, I found the description on the last example of chapter 5 very confusing.
As a beginner, at this point of the tutorial I had the mental model that a Parser always consumes/advdances the input.
Suddenly `take` is introduced without any further info, which uses checkpoints under the hood.
And to make this even more confusing, the output of the `parse_list` parser is changed to "accumulat[e] the results into a `()`", which really doesn't make a lot of sense if you don't know that `take` doesn't care about the output of the contained parser due to the checkpoint logic.
There's really a lot of concepts to unwrap in this small piece of code and it took a bit of research to figure out why stuff worked the way it does.
I hope the new text is able to convey this …

docs(tutorial): Clarify examples in chapter 5

---

src/combinator/multi.rs

I tried to do `.map(|()| ())` as suggested in the repeat_til documentation for taking a series of tokens. This gave me a compiler error saying that I needed to put a tuple instead for the args in the map. Switching to `.map(|((), _)| ())` fixed my problem, accumulating the Accumulator into nothing and discarding the result of the combinator that repeat_till took.
This was a stumbling block for me, and I thought this tweak might make things easier for the next person.
<details><summary>If you need more context, here is the code I wrote when going through this experience.</summary>
``` rust
fn discard_junk(input: &mut Stream) -> PResult<()> {
let mut parser = repeat_till(1.., take(1usize), peek(alt(("mul", "don't", "do"))))
.map(|((), _)| ())
.take()
.void();
parser.parse_next(input)
}
``` …

Documentaion fix for repeat_till

---

src/_topic/stream.rs
src/_topic/why.rs
src/lib.rs
src/parser.rs
src/stream/mod.rs

In #512, we found that the current name is so general it makes it sound
like it applies in all cases but doesn't.
Trying to make it clear that this is limited in where it can apply and is prep for #648.

fix(stream): Rename Located to LocatingSlice 

---

src/macros/seq.rs
src/macros/test.rs

Fixes #502
BREAKING CHANGE: When using `seq!(<tuple>)`, any local parsers must be
marked as `mut`

fix(seq)!: Allow borrowing of parsers in seq 

---

benches/iter.rs
examples/ndjson/main.rs
src/_topic/nom.rs
src/lib.rs
src/stream/mod.rs

Searching my projects, these are the ones I tend to see used and shouldn't cause much of a problem
Fixes #647
BREAKING CHANGE: These will cause unused import warnings when importing both the prelude and the trait

feat!: Add ParserError, AsChar, ContainsToken, Stream to prelude

---

src/ascii/mod.rs
src/ascii/tests.rs

This makes the problem easier to discover than ending early and is
consistent with `repeat`.
A parser that wants to end on an empty match can just turn an empty
match into an error.
Fixes #569

fix(ascii)!: Assert, rather than stop, escape on empty normal 

---

src/_topic/why.rs

Clean up some links in why.rs

---

examples/arithmetic/parser_lexer.rs
src/stream/mod.rs
src/token/mod.rs

fix(stream)!: Change ContainsToken from Fn to FnMut

---

src/combinator/parser.rs
src/parser.rs

Unsure how these were missed in #222.

fix(parser)!: Improve type inference for Parser::by_ref, Parser::complete_err

---

src/combinator/parser.rs
src/parser.rs

This reduces the boilerplate for writing an opaque `impl Parser`.  In this case, 240 lines.
I originally did the `new`s as I was thinking I might want to use it for other purposes and I was less comfortable with writing all of that PhantomData at the time (which only grew since with #222).

refactor(parser): Manually inline Parser struct new's

---

src/ascii/mod.rs
src/ascii/tests.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/binary/tests.rs
src/combinator/branch.rs
src/combinator/core.rs
src/combinator/multi.rs
src/combinator/tests.rs
src/lib.rs
src/parser.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/custom_errors.rs
tests/testsuite/float.rs
tests/testsuite/fnmut.rs
tests/testsuite/issues.rs
tests/testsuite/multiline.rs
tests/testsuite/overflow.rs
tests/testsuite/reborrow_fold.rs
tests/testsuite/utf8.rs

fix: De-emphasize `parse_peek`-related functionality

---

src/binary/bits/mod.rs
src/parser.rs

This is a partial cherry-pick of #676

fix: Deprecate `unpeek`

---

src/binary/bits/mod.rs
src/binary/bits/tests.rs

refactor(bits): Move off of unpeek

---

src/error.rs

refactor(error): Emphasize PResult over IResult

---

src/binary/bits/mod.rs
src/error.rs

fix(error): Move from ErrMode::Convert to ErrrorConvert::convert

---

src/combinator/multi.rs

Closes #99
Not sure if the documentation examples are good enough. In particular, I couldn't find any (non-nightly) simple examples for showcasing `try_fold`. Should we add something a bit more verbose or keep things simple?

feat(combinator): try_fold and verify_fold

---

src/lib.rs

Over-aggressive regex and missed this in the audit

fix(stream): Re-add re-export of Located in root

---

src/ascii/mod.rs
src/ascii/tests.rs

Really an excuse to remove `cut_err`

fix(ascii): Improve 'float' error quality by removing 'alt'

---

.github/workflows/ci.yml
src/_tutorial/chapter_2.rs
src/_tutorial/chapter_6.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/binary/tests.rs
src/combinator/branch.rs
src/combinator/core.rs
src/combinator/debug/mod.rs
src/combinator/multi.rs
src/combinator/sequence.rs
src/combinator/tests.rs
src/error.rs
src/lib.rs
src/macros/mod.rs
src/macros/tests.rs
src/parser.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/float.rs
tests/testsuite/issues.rs
tests/testsuite/main.rs
tests/testsuite/overflow.rs
tests/testsuite/reborrow_fold.rs
tests/testsuite/utf8.rs

Overall, this is to move us off of IResult and make it easier to change `ErrMode`

docs: Clean up examples

---

src/combinator/multi.rs
src/combinator/tests.rs

fix(comb): Fix repeat().fold(1..) to append errors

---

examples/arithmetic/parser_lexer.rs
src/stream/mod.rs
src/token/mod.rs

Revert "fix(stream)!: Change ContainsToken from Fn to FnMut"
This reverts commit 424f4b0014cd259115893521c84d2a8ac867ff2a.
When used with `const`, this produces warnings and I'd like more time to think on this.

fix(stream)!: Change ContainsToken from FnMut to Fn

---

src/ascii/mod.rs
src/ascii/tests.rs

fix(ascii): Allow separate normal/transform types for escaped_transform

---

examples/json/parser_dispatch.rs

Its not needed when `dispatch` is used since the failure location / cause is preserved.

docs(examples): Remove cut_err from dispatch example

---

src/binary/bits/mod.rs
src/combinator/debug/internals.rs
src/combinator/impls.rs
src/error.rs
src/stream/recoverable.rs

This is mostly focused on smoothing out `ErrMode::is_incomplete` to `ParserError::is_incomplete` so we can remove the former
This has breaking changes from `main` but not from a prior release

fix(error): Polish Incomplete handling

---

src/ascii/mod.rs
src/ascii/tests.rs

fix(ascii): Rename escaped_transform to escaped

---

src/ascii/mod.rs
src/ascii/tests.rs
src/binary/tests.rs
src/combinator/tests.rs
src/parser.rs
src/stream/mod.rs
src/stream/tests.rs
src/stream/token.rs
src/token/mod.rs
src/token/tests.rs

I was hoping to get `ContainsToken` support but I'm not seeing a reasonable
way of restructuring the traits without being blocked by the compiler
(overlapping impls) or having other side effects (less ergonomic for
other users).
`Compare` gets us the basics though.  The `Fn(&Token<'_>) -> bool`
variant of `ContainsToken` should still work and people can add their
own `Compare`s to get tuples working.
Also, didn't see a way to get a `impl Parser for TokenKind` to work
for similar reasons.
Location tracking is inspired by #512 and #591
Fixes #637
Fixes #590

feat(stream)!: Add `TokenSlice` to make parsing lexed tokens easier

---

src/error.rs

docs(ref): Link ContextError to tutorial

---

src/_tutorial/chapter_7.rs
src/error.rs

This simplifies adapting parse errors to application errors.

feat(error): Provide ParseError::char_span

---

src/combinator/multi.rs

refactor(comb): Clean up `repeat` parsers

---

src/_topic/partial.rs

ndjson domain is pointing to malicious site. I think linking to their github is more appropriate.
https://github.com/ndjson/ndjson-spec/issues/35#issuecomment-1285673417

Replace ndjson link in topic

---

examples/arithmetic/parser_lexer.rs
examples/arithmetic/test_parser_lexer.rs
src/combinator/debug/internals.rs
src/lib.rs
src/stream/bstr.rs
src/stream/bytes.rs
src/stream/locating.rs
src/stream/mod.rs
src/stream/stateful.rs
src/stream/token.rs

feat(stream): Give streams direct control over 'trace' output

---

Cargo.lock
Cargo.toml
src/combinator/debug/internals.rs

refactor(debug): Don't pull in is-terminal when its not needed

---

src/stream/mod.rs

Allows combinators like `repeat` to accumulate into a `VecDeque`. Implementation follows that of `Vec`.

feat(stream): Implement Accumulate for VecDeque

---

src/branch.rs
src/bytes.rs
src/lib.rs
src/sequence.rs

It turns out we weren't always showing `deprecated` messages because of rust-lang/rust#47237

fix: Show more deprecated messages
