winnow-rs/winnow

src/bytes/complete.rs
src/bytes/streaming.rs
src/character/complete.rs
src/character/streaming.rs
src/core.rs
src/internal.rs
src/lib.rs
src/number/streaming.rs
src/traits.rs

This is prep for Geal/nom#1535

fix!: Split InputTakeAtPosition into complete/partial traits

---

src/branch/mod.rs

refactor(branch): Put all macros next to each other

---

src/multi/mod.rs

fix(multi): Switch 'fill' from taking Fn to Parser

---

src/combinator/mod.rs

You could make a `ParserIterator` but you couldn't iterate over it.
BREAKING CHANGE: `ParserIterator` gained an additional generic parameter

fix(comb)!: Allow ParserIterator on parsers

---

src/bits/mod.rs

fix(bits): Accept Parser, not parser-like functions

---

.clippy.toml
.github/workflows/ci.yml
Cargo.toml
README.md
src/input.rs

fix: Support byte arrays of any size

---

src/input.rs

fix(input): Decouple the TakeAt traits

---

src/input.rs

This isn't a proper input type, so no idea why its here.  It was added in fa8dc950b02661084d4d2d2ace3661ac7e233fa8 but no tests fail removing it.

fix(input)!: Remove `impl ExtendInto for char`

---

src/number/complete.rs
src/number/streaming.rs

fix(number): Prep for merging complete/streaming

---

src/multi/mod.rs

This was originally copied from `length_value` and Geal/nom#1033 tried to fix it but it really should just be removed.  This function does not affect incomplete.

docs(multi): Remove bad length_data comment

---

src/combinator/mod.rs
src/parser.rs

This is prep for putting more of an emphasis on them as part of Geal/nom#1408

docs(parser): Clean up `Parser` function docs

---

src/combinator/mod.rs
src/multi/mod.rs

docs(combinator): Clarify role of 'cut'

---

src/_cookbook.rs
src/combinator/mod.rs

This was missed as part of #28

docs: Point to generic parsers, not complete

---

src/multi/tests.rs
src/sequence/mod.rs
src/sequence/tests.rs
tests/arithmetic.rs
tests/float.rs
tests/ini.rs
tests/ini_str.rs
tests/issues.rs

fix(seq): Deprecate pair

---

.github/workflows/ci.yml
benchmarks/benches/arithmetic.rs
benchmarks/benches/http.rs
benchmarks/benches/ini.rs
benchmarks/benches/ini_str.rs
benchmarks/benches/json.rs
benchmarks/benches/number.rs

test: Update benches for changes

---

src/input.rs

refactor(input): Be more consistent in layout

---

src/error.rs

This is a compatibility hazard and offers little value
Looking to add a new ErrorKind and it didn't seem worth finagling things to work.  Logically, it belongs next to another error kind but the numbering prevents that.

fix(error)!: Remove error_to_u32

---

benchmarks/benches/arithmetic.rs
benchmarks/benches/http.rs
benchmarks/benches/ini.rs
benchmarks/benches/ini_str.rs
benchmarks/benches/json.rs
benchmarks/benches/number.rs

Just change the `Input` type def, the constructor, and away you go!

refactor(bench): Make it easier to try alternative parsers

---

src/input.rs
src/multi/mod.rs

This is general cleanup in preparation for location / state support

fix(input): Allow reconstructing input state

---

src/input.rs

`nom-locate` built state support directly into the located input, whether people needed it or not.  `pori` takes the approach of providing them as separate types.  By baking this in directly, we allow people to compose different input wrappers as needed.

feat(input): Thread state through parsing

---

src/input.rs

fix(input): impl FindSubstring for Stateful

---

src/input.rs

fix(input): Generalize Streaming's InputTakeAtPosition

---

CHANGELOG.md
src/bits/complete.rs
src/bits/mod.rs
src/bits/streaming.rs
src/bits/tests.rs
src/error.rs
src/input.rs
src/multi/mod.rs
src/number/complete.rs
src/number/mod.rs

This updates nom8 for everything in the 7.1.1 tag.

feat: Merge tag `7.1.1`

---

src/combinator/mod.rs

docs(ref): Add missing bits combinators

---

CHANGELOG.md
src/multi/mod.rs
tests/issues.rs

fix: Merge in nom 7.1.3

---

examples/s_expression.rs
src/_tutorial.rs

This is for rust-bakery/nom#1425 which we already supported in #42

Merge nom v8 (commit 'c3e945a')

---

examples/http/bench.rs
examples/http/parser_streaming.rs
examples/json/bench.rs
examples/json/main.rs
examples/json/parser_streaming.rs

This cherry-picks Geal/nom#1609, adapted for #77

add streaming benchmarks (#1609)

---

src/branch/mod.rs
src/bytes/complete.rs
src/bytes/mod.rs
src/bytes/streaming.rs
src/combinator/mod.rs
src/sequence/mod.rs

Unsure how this was missed in 9194d76

refactor: Normalize generic parameters

---

src/input.rs

Inspired by rust-bakery/nom#1520

fix(input): Clarify Offset with an explicit assert

---

src/bits/complete.rs
src/bytes/complete.rs
src/bytes/streaming.rs
src/character/complete.rs
src/character/streaming.rs
src/character/tests.rs
src/combinator/mod.rs
src/error.rs
src/input.rs
src/multi/mod.rs
src/number/complete.rs
src/number/streaming.rs

feat(error): Centralize backtracking policy

---

src/bits/mod.rs
src/combinator/mod.rs
src/error.rs

feat(error): Further consolidate on `ErrMode`

---

.github/workflows/ci.yml
src/error.rs

fix(error): Adjust for alloc

---

Cargo.toml
examples/json/main.rs
examples/json_iterator.rs
src/bytes/complete.rs
src/character/tests.rs
src/number/complete.rs
tests/testsuite/utf8.rs

chore: Resolve warnings

---

src/bits/complete.rs
src/bits/streaming.rs
src/bytes/complete.rs
src/bytes/streaming.rs
src/character/complete.rs
src/character/mod.rs
src/character/streaming.rs
src/combinator/mod.rs
src/error.rs
src/number/complete.rs
src/number/streaming.rs
src/parser.rs
src/sequence/mod.rs

docs: Update deprecations for not being nom v8

---

src/bytes/mod.rs
src/input.rs

docs: Misc improvements

---

src/combinator/mod.rs

feat(comb): Add `todo` combinator

---

benches/number.rs
src/character/complete.rs
src/character/mod.rs
src/character/streaming.rs
src/character/tests.rs
src/combinator/mod.rs
src/input.rs
src/number/complete.rs
src/number/streaming.rs
src/parser.rs

feat(parser)!: Add `ParseTo` combinator

---

examples/json/bench.rs
src/bits/streaming.rs
src/bits/tests.rs
src/branch/tests.rs
src/bytes/mod.rs
src/bytes/streaming.rs
src/bytes/tests.rs
src/character/mod.rs
src/character/streaming.rs
src/character/tests.rs
src/combinator/tests.rs
src/error.rs
src/lib.rs
src/multi/tests.rs
src/number/mod.rs
src/number/streaming.rs
src/number/tests.rs
src/parser.rs
src/sequence/tests.rs
tests/testsuite/custom_errors.rs
tests/testsuite/issues.rs
tests/testsuite/overflow.rs
tests/testsuite/utf8.rs

fix(input): Put common types in root namespace

---

src/combinator/mod.rs
src/error.rs
src/lib.rs
src/parser.rs

docs: Fix stale references

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml

chore(ci): Verify against miri

---

src/stream/impls.rs

fix(stream): Provide `BStr` alternative for future debug system

---

src/stream/mod.rs

refactor(stream): Remove redundant impl bodies

---

src/stream/mod.rs

fix(stream): Implement AsBStr for BStr

---

src/combinator/mod.rs
src/parser.rs

fix(parser)!: Require `Debug` for `Context`

---

src/stream/mod.rs

This will help with debugging in #156

feat(stream)!: All streams are guarenteed to support `Offset`

---

src/stream/mod.rs

This will help with debugging in #156

feat(stream)!: Make `Stream::Token` and `Stream::Slice` debuggable

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml
src/bytes/tests.rs
src/character/complete.rs
src/character/streaming.rs
src/character/tests.rs
src/number/complete.rs
src/number/streaming.rs
src/stream/tests.rs

chore(ci): Actually test miri

---

src/number/mod.rs

This is prep for adding tracing

fix(number)!: Change parsers to return `FnMut`

---

src/number/mod.rs

fix(trace): Add missing traces

---

Cargo.toml

I missed this with the interaction of #160 and #156

fix: Hide optional dependencies

---

src/_tutorial.rs
src/combinator/mod.rs
src/error.rs
src/parser.rs
src/stream/mod.rs
tests/testsuite/issues.rs

fix(error)!: Deprecate `dbg_dmp` in favor of `trace`

---

Cargo.lock
Cargo.toml
assets/trace.svg
deny.toml
src/trace/mod.rs

docs(trace): Expand on trace documentation

---

Cargo.lock
Cargo.toml
doc/home.md
examples/iterator.rs
examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_arithmetic.rs
src/_tutorial.rs
src/character/complete.rs
src/character/streaming.rs
src/combinator/mod.rs
src/error.rs
src/stream/mod.rs

docs: Remove 'nom' from everything

---

Cargo.lock
Cargo.toml
src/trace/mod.rs

refactor(tests): Drop number of dev deps

---

src/_topic/mod.rs
src/_topic/why.rs
src/lib.rs

docs(topci): Start explaining "why?"

---

src/_topic/why.rs

docs(topic): Add a chumsky comparison

---

src/error.rs
src/lib.rs
src/stream/mod.rs

fox: Ease the nom migration burden

---

assets/trace.svg
src/trace/internals.rs
src/trace/mod.rs

fix(trace): Don't show colors when piped

---

examples/css/parser.rs

docs: Simplify starting example

---

src/combinator/mod.rs

docs: Last minute tweaks

---

src/stream/mod.rs

refactor(stream): Minor `next_slice` clean up I thought of

---

src/stream/mod.rs

refactor(stream): Prefer higher level split_first

---

src/multi/mod.rs
src/multi/tests.rs
src/stream/mod.rs
src/stream/tests.rs

The patch and test fixes for #203.

Set `Partial` complete after `Partial::complete()` is called

---

src/bytes/mod.rs
src/bytes/tests.rs

fix!: Treat take_while_m_n bad range as assert

---

src/number/mod.rs

refactor(num): Delegate to other parsers

---

src/multi/mod.rs
src/multi/tests.rs

fix!: Turn infinite loop errors into asserts

---

src/bits/mod.rs
tests/testsuite/issues.rs

fix(bits)!: Turn overflow into an assert

---

assets/trace.svg
src/branch/mod.rs
src/bytes/mod.rs
src/bytes/tests.rs
src/character/mod.rs
src/character/tests.rs
src/multi/mod.rs
src/parser.rs
tests/testsuite/issues.rs

refactor: Simplify parsing code

---

Cargo.toml
benches/contains_token.rs

bench: Verify relative difference in ContainsToken impls

---

src/_topic/mod.rs
src/_topic/performance.rs

docs(perf): Write down initial perf notes

---

src/branch.rs
src/multi.rs
src/sequence.rs
tests/testsuite/overflow.rs

Technically, its a minor incompat (I think) but we should still play nice.

fix: Reduce chance of breakage from wildcard imports

---

Cargo.lock
Cargo.toml
src/trace/internals.rs

This fixes a bug with `NO_COLOR` and `CLICOLOR`

fix(debug): Improve control over colors

---

src/token/mod.rs

Its hard to tell due to jitter but I don't think there is a performance regression, judghing by `json/canada`

refactor(token): Remove extra layers

---

src/ascii/mod.rs
src/binary/mod.rs
src/token/mod.rs

refactor: Remove unused pub(crate)s

---

src/ascii/mod.rs

refactor(ascii): Simplify expressions

---

src/stream/mod.rs

style: Make clippy happy

---

src/ascii/mod.rs
src/combinator/parser.rs
src/parser.rs

refactor: Remove redundant trait bounds

---

examples/ndjson/main.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/combinator/core.rs
src/combinator/parser.rs
src/combinator/tests.rs
src/error.rs
src/stream/mod.rs
src/stream/tests.rs
src/token/mod.rs
src/trace/mod.rs

These are some refactors in prep for `Checkpoint`s that I think are worth doing even if we decide against `Checkpoint`s

fix(stream)!: Prep for `Checkpoint`s

---

src/ascii/tests.rs
src/error.rs
src/stream/mod.rs
src/stream/tests.rs

This is more `Checkpoint` prep

fix(stream)!: Remove convenience Offset impls

---

src/ascii/mod.rs
src/combinator/parser.rs
src/stream/mod.rs
src/trace/mod.rs

The goal is to work towards #72.  I originally held off on this in case #72 doesn't work out but after going through all of these changes, I feel like there can be some value in this.
Preliminary benchmarking shows no change but that is with having to do multiple runs to try to control for jitter so its not too exact
Prep for this included
- #259 
- #258 
- #257
- #256

feat(stream)!: Add checkpointing to `Stream`

---

src/stream/mod.rs
src/token/mod.rs

refactor(token): Move helpers closer to use

---

src/error.rs

feat(error): Allow ErrorKind as a ParseError

---

Cargo.lock
Cargo.toml
fuzz/Cargo.toml

chore: Upgrade dependencies

---

examples/json/bench.rs

test(json): Use correct stream type

---

examples/json/bench.rs

test(json): Cover unit error as well

---

src/_topic/language.rs

docs(topic): Link out to relevant builtin parsers

---

Cargo.lock
Cargo.toml
fuzz/Cargo.toml
src/_topic/language.rs
src/ascii/mod.rs
src/ascii/tests.rs

fix: Backport changes to 0.4

---

src/combinator/branch.rs

fix(comb): Report original error location for alt

---

src/_topic/performance.rs

docs(topic): Clean up typos in performance section

---

src/_tutorial/chapter_0.rs
src/_tutorial/chapter_1.rs
src/_tutorial/chapter_2.rs
src/_tutorial/chapter_3.rs
src/_tutorial/chapter_4.rs
src/_tutorial/chapter_5.rs
src/_tutorial/chapter_6.rs
src/_tutorial/chapter_7.rs

docs(tutorial): Add links to ToC

---

src/error.rs

feat(error): Allow displaying TreeError

---

src/error.rs

This also better aligns the different error types

feat(error): Add VerboseError to help migration

---

src/error.rs

fix(error): Improve rendering of error kind

---

src/error.rs

feat(error): Impl Display for StrContext

---

src/combinator/parser.rs
src/error.rs
src/parser.rs

perf: Inline more things

---

src/combinator/parser.rs
src/error.rs
src/parser.rs

This is to help narrow down some regressions in gitoxide

perf: Backport inlining from 0.5 to 0.4

---

src/error.rs
src/stream/mod.rs

perf: Backport 0.5 improvements

---

src/macros.rs

Inspired by https://internals.rust-lang.org/t/pub-on-macro-rules/19358/16

docs: Hide dispatch within the root

---

src/_topic/mod.rs
src/_tutorial/mod.rs
src/error.rs
src/lib.rs
src/trace/mod.rs

chore(ci): Catch core/std issues earlier

---

src/error.rs

docs(ref): Clarify IResult/PResult

---

src/stream/mod.rs

docs: Clarify spans

---

src/_tutorial/chapter_0.rs
src/_tutorial/chapter_1.rs

Fixes minor typos in tutorial.

docs: fix typo in tutorial

---

Cargo.toml
examples/arithmetic/bench.rs
examples/arithmetic/main.rs
examples/arithmetic/parser.rs
examples/arithmetic/parser_ast.rs
examples/arithmetic/parser_lexer.rs
src/_topic/arithmetic.rs
src/_topic/mod.rs
src/_topic/stream.rs
src/stream/mod.rs

In particular, this shows what is needed to support custom tokens

docs(examples): Add lexer/parser example

---

src/_tutorial/chapter_4.rs

This seems to be an outdated comment from the time when `IResult` still contained the new input.
Please close if indeed correct.

docs: fix outdated tutorial

---

src/combinator/mod.rs

Fix broken markdown table after https://github.com/winnow-rs/winnow/pull/350 🤦

docs: fix list of combinators

---

examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
examples/ndjson/parser.rs
src/error.rs

fix(docs): rename old names

---

src/combinator/multi.rs

Minor reordering of functions in combinator to facilitate adding #362.
Split out from #362.

fix(combinator): reorder repeat

---

assets/trace.svg
benches/contains_token.rs
examples/ini/parser_str.rs
examples/string/parser.rs
src/ascii/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/issues.rs
tests/testsuite/reborrow_fold.rs
tests/testsuite/utf8.rs

feat(token): Add take_till 

---

src/stream/mod.rs

We can't update `not_line_ending` until a breaking change due to a change in trait bounds

feat(token): Allow match 1-3 items with `take_until`

---

src/ascii/mod.rs
src/stream/mod.rs

refactor(token): Clear up tag code

---

src/error.rs
src/stream/mod.rs

fix(error): Point to right location for single-line errors 

---

Cargo.toml
src/_topic/mod.rs
src/_topic/nom.rs
src/_topic/why.rs
src/lib.rs

docs: Add nom migration guide

---

src/combinator/mod.rs

Fix a couple typos in combinator/mod.rs

---

src/_topic/partial.rs
src/combinator/mod.rs
src/combinator/parser.rs
src/parser.rs

feat: Add Parser::default_value

---

Cargo.toml
benches/next_slice.rs
src/stream/mod.rs
src/stream/tests.rs

On merge, we'll need to create an issue to switch `impl Parser for char` to this as it is significantly faster
Fixes #407

feat(token): `tag` combinator support `char` type

---

benches/find_slice.rs
src/_topic/language.rs
src/_topic/partial.rs
src/combinator/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/utf8.rs

fix: Generalize take_until* to take_until

---

src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/tests.rs
tests/testsuite/overflow.rs

fix(comb): Generalize repeat_till0 as repeat_till

---

src/stream/mod.rs

docs(stream): Connect Location to Located

---

Cargo.toml
src/combinator/parser.rs
src/error.rs
src/lib.rs
src/parser.rs
src/stream/mod.rs

The main things this leave out include:
- A happy path for error reporting
- Examples
First step towards #96

feat: Unstable support for error recovery

---

src/combinator/multi.rs
src/error.rs
src/token/mod.rs

fix(comb)!: Be consistent in asserting on programmer error

---

src/_topic/language.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/combinator/mod.rs
src/token/mod.rs

perf(ascii): Use simd for till_line_ending

---

src/macros/seq.rs

docs: Hide seq macro in crate root

---

src/binary/bits/mod.rs
src/lib.rs
src/stream/mod.rs
src/token/mod.rs
src/token/tests.rs
tests/testsuite/main.rs

In looking over these, changes, we should make the core of these are available in v0.5.

Backport v0.6 changes

---

src/stream/mod.rs

refactor(stream): Implement AsChar refs in terms of concrete types

---

src/ascii/mod.rs

refactor(ascii): Use void parser

---

src/stream/mod.rs
src/token/mod.rs

This would allow for inclusive `take_until`

fix(stream): Allow knowing the end of the range

---

assets/trace.svg
src/token/mod.rs

fix(token): Update trace for tag->literal rename

---

assets/trace.svg
src/combinator/debug/mod.rs
src/token/mod.rs

fix(debug): Show literals in the traces

---

src/ascii/mod.rs
src/stream/mod.rs

fix(stream)!: Prevent slicing on non-UTF8 boundaries 

---

src/stream/mod.rs

This is to smooth out the upgrade to 0.6 as some of the imps will be removed and these are needed to replace them

feat(stream): Allow finding chars in byte slices

---

src/ascii/mod.rs
src/ascii/tests.rs
src/combinator/multi.rs

feat(ascii): Add usize/isize dec int parsing

---

src/binary/bits/mod.rs
src/token/mod.rs

fix!: Remove tag

---

src/ascii/mod.rs
src/ascii/tests.rs

fix(ascii): Accept 0 with dec_uint/dec_int

---

src/combinator/tests.rs

test: Update for asserts being cut

---

src/stream/mod.rs

docs: Fix a couple of typos

---

examples/json_iterator.rs
src/_topic/language.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/binary/bits/mod.rs
src/binary/mod.rs
src/combinator/core.rs
src/combinator/mod.rs
src/token/mod.rs

docs: Further clarify APIs

---

Cargo.lock
Cargo.toml

Hey I was comparing this project with nom and noticed you had an useless dependency in your `Cargo.toml`

Remove useless escargot dependency

---

src/stream/mod.rs

fix(debug): Improve traces for wrapped Inputs

---

Cargo.lock
Cargo.toml

chore: Upgrade snapbox to 0.6

---

src/macros/seq.rs

feat: Allow seq! accept multi-segments path

---

src/_tutorial/chapter_1.rs

docs(tutorial): Clean up connections to future topics

---

src/macros/seq.rs
src/macros/test.rs

Inspired by winnow-rs/winnow#534

fix(comb): Clarify `seq`s behavior

---

Cargo.lock
Cargo.toml
examples/custom_error.rs
src/_topic/error.rs
src/_tutorial/chapter_1.rs
src/_tutorial/chapter_3.rs
src/_tutorial/chapter_6.rs
src/_tutorial/chapter_7.rs
src/combinator/branch.rs
src/combinator/core.rs

Inspired by winnow-rs/winnow#537

docs: Round out our error documentation

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml

Things are too slow, taking a powerset of features.

chore(ci): Speed up CI

---

src/_tutorial/chapter_1.rs

Removed a single char to fix alignment

Fix tutorial parser return schema alignment

---

Cargo.lock
Cargo.toml
src/_tutorial/chapter_6.rs

docs(tutorial): Be more explicit about ParseError's role

---

examples/json/bench.rs
examples/json/parser.rs
examples/json/parser_dispatch.rs
examples/json/parser_partial.rs
examples/ndjson/main.rs
examples/ndjson/parser.rs

docs(examples): Switch to ContextError (default) 

---

examples/ndjson/main.rs

docs(examples): Avoid parse_peek in production code

---

CHANGELOG.md
src/_topic/nom.rs

docs(changelog): Give hint on resolving type inference issues 

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

My apologies for not opening an issue about these, but I didn't think they warranted discussion, as they're obviously wrong.
I found these with a different spellcheck.

A couple of typo fixes

---

.github/renovate.json5
.github/workflows/ci.yml
CONTRIBUTING.md
Cargo.toml
benches/iter.rs
deny.toml
examples/s_expression/parser.rs
src/combinator/core.rs
src/combinator/parser.rs
src/error.rs
src/parser.rs
src/stream/impls.rs
src/stream/mod.rs

chore: Update from _rust template

---

src/combinator/branch.rs
src/combinator/core.rs
src/error.rs
src/parser.rs
src/stream/mod.rs

perf: Further tweak inlining

---

src/combinator/parser.rs
src/stream/mod.rs

fix(stream)!: Allow asking tokens for their spans

---

src/token/mod.rs

I don't think we have tests for `is_partial` handling, so keeping with that poor behavior.
Fixes #651

fix(token): Respect 'is_partial' in 'take_till'

---

src/macros/seq.rs
src/parser.rs

refactor: Macro clean up

---

src/macros/seq.rs

refactor(seq): More macro cleanup

---

fuzz/fuzz_targets/fuzz_arithmetic.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/binary/bits/mod.rs
src/binary/bits/tests.rs
src/binary/mod.rs
src/binary/tests.rs
src/combinator/branch.rs
src/combinator/multi.rs
src/combinator/sequence.rs
src/combinator/tests.rs
src/error.rs
src/parser.rs
src/stream/tests.rs
src/token/mod.rs
src/token/tests.rs

fix(error)!: Rename kinds Tag->Literal, Many->Repeat

---

src/stream/mod.rs

This reverts commit 680b41a341b24bc1719ad560fd06e002e3ea9141.
PR #514 was meant to help #482 but I can't reproduce the problem

Revert "fix(debug): Improve traces for wrapped Inputs"

---

src/_topic/why.rs

This was cherry-picked from #664

Clean up some links in why.rs

---

examples/json/parser_partial.rs
src/_topic/nom.rs
src/binary/bits/mod.rs
src/combinator/core.rs
src/combinator/tests.rs
src/parser.rs
src/token/mod.rs
src/token/tests.rs

fix(token): Move rest/rest_len from combinator 

---

src/ascii/mod.rs

fix(ascii)!: Remove unused lifetime

---

src/ascii/mod.rs
src/combinator/impls.rs

refactor: Clean up ErrMode logic

---

src/combinator/multi.rs
src/error.rs

This cherry-picks
- #682
- Parts of #683
- #685

feat(combinator): try_fold and verify_fold 

---

src/binary/bits/mod.rs
src/combinator/core.rs
src/error.rs

refactor: Minor clean up

---

assets/trace.svg
src/_tutorial/chapter_8.rs
src/combinator/debug/mod.rs

docs(tutorial): Make some connections explicit for traces

---

Cargo.lock
Cargo.toml
src/ascii/tests.rs
src/binary/tests.rs
src/combinator/tests.rs
src/macros/tests.rs
src/parser.rs
src/token/tests.rs
tests/testsuite/float.rs
tests/testsuite/issues.rs
tests/testsuite/overflow.rs
tests/testsuite/utf8.rs

test: Switch to raw snapshots

---

examples/custom_error.rs
src/combinator/tests.rs
src/error.rs

feat(error): Add inherent ParserError::append

---

src/error.rs
src/parser.rs
tests/testsuite/issues.rs

feat(error): Allow using TreeErrors on bits

---

src/binary/bits/mod.rs
src/binary/mod.rs

refactor(error): Leverage ErrMode impl

---

Cargo.lock
Cargo.toml
src/lib.rs

test: Drop doc-comment dep

---

src/_topic/nom.rs
src/_topic/why.rs

docs(topics): Discuss nom's use of GATs

---

examples/json/parser_dispatch.rs
src/_topic/nom.rs
src/_topic/why.rs
src/error.rs
src/lib.rs
src/parser.rs

Smooth out v0.7 migration

---

examples/custom_error.rs
src/ascii/mod.rs
src/ascii/tests.rs
src/binary/tests.rs
src/combinator/branch.rs
src/combinator/core.rs
src/combinator/impls.rs
src/combinator/mod.rs
src/combinator/multi.rs
src/combinator/tests.rs
src/error.rs
src/lib.rs
src/macros/tests.rs
src/parser.rs
src/stream/mod.rs
src/token/tests.rs
tests/testsuite/custom_errors.rs
tests/testsuite/issues.rs
tests/testsuite/utf8.rs

fix!: Remolve deprecated code

---

src/_topic/language.rs
src/stream/bstr.rs
src/stream/bytes.rs
src/stream/locating.rs
src/stream/mod.rs
src/stream/partial.rs
src/stream/recoverable.rs
src/stream/stateful.rs
src/stream/tests.rs

fix(stream)!: Don't return input on peek

---

src/_topic/nom.rs

This is based on feedback from #717

docs(topic): Clarify and cleanup nom topic

---

src/error.rs

Based on feedback from nextest-rs/nextest#2109

docs(error): Clarify ErrMode

---

src/combinator/core.rs

fix(comb): Prevent misuse of 'iterator' from panicking

---

src/stream/range.rs

feat: Allow Range to be copied

---

src/_tutorial/chapter_7.rs

Addressing feedback in #748
Would like to improve and better highlight our lexing/parsing example

docs(tutorial): Clear up suggestions on spans

---

src/combinator/mod.rs
src/macros/dispatch.rs

docs: Clarify parsers

---

src/_topic/language.rs

Remove useless braces in docs

---

src/stream/token.rs

This is something I've been thinking about for a while.  Unsure what exact shape it should take but this is at least a starting point.

feat(stream): Add access to previous tokens

---

examples/iterator.rs
src/_topic/nom.rs
src/_tutorial/chapter_5.rs
src/_tutorial/chapter_6.rs
src/combinator/multi.rs
src/lib.rs

style: Help catch 'alloc' mistakes

---

src/stream/locating.rs
src/stream/stateful.rs

fix(stream): Make raw() inner-most

---

src/_topic/stream.rs
src/_tutorial/chapter_1.rs
src/_tutorial/chapter_2.rs
src/_tutorial/chapter_8.rs
src/lib.rs
src/stream/token.rs

docs: Improve lexing/parsing docs

---

src/combinator/impls.rs
src/error.rs
src/parser.rs

feat(parser): Add Parser::map_err 

---

.cargo/config.toml
.github/workflows/ci.yml
.github/workflows/rust-next.yml
Cargo.toml
examples/arithmetic/parser_lexer.rs
src/ascii/mod.rs

chore: Update from _rust/main template

---

src/combinator/impls.rs
src/error.rs
src/parser.rs

feat(parser): Add Parser::context_with

---

src/macros/mod.rs
src/stream/bstr.rs
src/stream/bytes.rs

fix(stream): Don't overflow stack on PartialEq/PartialOrd
